Repository THEGOODs-repo/server, pull requests merged in 2024-02, with the labels that each got.

#34 [feature/22] 구매자 주문 조회 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
  src/main/java/com/umc/TheGoods/domain/enums/OrderStatus.java
  src/main/java/com/umc/TheGoods/domain/order/OrderItem.java
  src/main/java/com/umc/TheGoods/repository/order/OrderDetailRepository.java
  src/main/java/com/umc/TheGoods/repository/order/OrderItemRepository.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandService.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryService.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/validation/annotation/CheckPage.java
  src/main/java/com/umc/TheGoods/validation/annotation/ExistOrders.java
  src/main/java/com/umc/TheGoods/validation/validator/CheckPageValidator.java
  src/main/java/com/umc/TheGoods/validation/validator/OrderAvailableValidator.java
  src/main/java/com/umc/TheGoods/validation/validator/OrdersExistValidator.java
  src/main/java/com/umc/TheGoods/web/controller/OrderController.java
  src/main/java/com/umc/TheGoods/web/dto/order/OrderRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/order/OrderResponseDTO.java
Labels: :sparkles: feature

#39 [refactor/38] Cart, Item 엔티티 및 OrderStatus 변경
  src/main/java/com/umc/TheGoods/domain/enums/OrderStatus.java
  src/main/java/com/umc/TheGoods/domain/item/Item.java
  src/main/java/com/umc/TheGoods/domain/order/Cart.java
Labels: :recycle: refactor

#41 [feature/40] 주문 구매 확정 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
  src/main/java/com/umc/TheGoods/domain/order/OrderItem.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandService.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/OrderController.java
  src/main/java/com/umc/TheGoods/web/dto/order/OrderRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/order/OrderResponseDTO.java
Labels: :sparkles: feature

#43 [feature/42] 장바구니 등록 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/domain/order/Cart.java
  src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/validation/annotation/ExistItem.java
  src/main/java/com/umc/TheGoods/validation/annotation/ExistItemOption.java
  src/main/java/com/umc/TheGoods/validation/validator/ItemExistValidator.java
  src/main/java/com/umc/TheGoods/validation/validator/ItemOptionExistValidator.java
  src/main/java/com/umc/TheGoods/validation/validator/OrderAvailableValidator.java
  src/main/java/com/umc/TheGoods/web/controller/CartController.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
Labels: :sparkles: feature

#45 [feature/44] 장바구니 옵션 수정 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/domain/order/Cart.java
  src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/validation/annotation/ExistCart.java
  src/main/java/com/umc/TheGoods/validation/validator/CartExistValidator.java
  src/main/java/com/umc/TheGoods/web/controller/CartController.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
Labels: :sparkles: feature

#49 [Ci/46] CI/CD 파이프라인 구축 테스트
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  build.gradle
  src/main/java/com/umc/TheGoods/web/controller/RootController.java
  src/main/resources/application.yml
Labels: :computer: ci

#50 :construction_worker: CI/CD: client_max_body_size.conf 수정
  .platform/nginx/conf.d/client_max_body_size.conf
Labels: :computer: ci

#52 :construction_worker: CI/CD: application.yml 수정
  src/main/resources/application.yml
Labels: :computer: ci

#53 :construction_worker: CI/CD: KST timezone 설정
  .ebextensions_dev/00-makeFiles.config
Labels: :computer: ci

#57 [feature/10] 인기 피드 전체 조회
  src/main/java/com/umc/TheGoods/domain/community/Comment.java
  src/main/java/com/umc/TheGoods/domain/community/Inquiry.java
  src/main/java/com/umc/TheGoods/domain/member/Member.java
  src/main/java/com/umc/TheGoods/repository/PostRepository.java
  src/main/java/com/umc/TheGoods/service/.gitkeep
  src/main/java/com/umc/TheGoods/service/PostService/PostCommandService.java
  src/main/java/com/umc/TheGoods/service/PostService/PostCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/PostService/PostQueryService.java
  src/main/java/com/umc/TheGoods/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/PostController.java
  src/main/java/com/umc/TheGoods/web/dto/.gitkeep
  src/main/java/com/umc/TheGoods/web/dto/post/PostRequestDto.java
  src/main/java/com/umc/TheGoods/web/dto/post/PostResponseDto.java
Labels: :sparkles: feature

#62 :construction_worker: CI/CD: application.yml db 설정 정보 수정
  .ebextensions_dev/00-makeFiles.config
  src/main/resources/application.yml
Labels: :computer: ci

#63 :construction_worker: CI/CD: application.yml 파일 분리
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: :computer: ci

#54 [feature] 상품 정보 수정 API & 상품 상세 정보 조회 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
  src/main/java/com/umc/TheGoods/converter/item/ItemViewConverter.java
  src/main/java/com/umc/TheGoods/domain/item/Item.java
  src/main/java/com/umc/TheGoods/domain/mapping/ViewSearch/ItemView.java
  src/main/java/com/umc/TheGoods/repository/item/ItemImgRepository.java
  src/main/java/com/umc/TheGoods/repository/item/ItemOptionRepository.java
  src/main/java/com/umc/TheGoods/repository/item/ItemTagRepository.java
  src/main/java/com/umc/TheGoods/repository/item/ItemViewRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
  src/main/java/com/umc/TheGoods/web/dto/item/ItemRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/item/ItemResponseDTO.java
Labels: :sparkles: feature

#66 [feature] 판매 상품 조회 API 구현
  src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
  src/main/java/com/umc/TheGoods/web/dto/item/ItemResponseDTO.java
Labels: :sparkles: feature

#76 [feature/67] 장바구니 조회 API 구현 & 장바구니 등록/수정 API 수정
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/domain/item/ItemOption.java
  src/main/java/com/umc/TheGoods/domain/order/Cart.java
  src/main/java/com/umc/TheGoods/domain/order/CartDetail.java
  src/main/java/com/umc/TheGoods/repository/cart/CartDetailRepository.java
  src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/validation/annotation/ExistCartDetail.java
  src/main/java/com/umc/TheGoods/validation/validator/CartDetailExistValidator.java
  src/main/java/com/umc/TheGoods/web/controller/CartController.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature

#86 [feature] 상품 검색 기능 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/tag/TagSearchConverter.java
  src/main/java/com/umc/TheGoods/domain/mapping/ViewSearch/TagSearch.java
  src/main/java/com/umc/TheGoods/repository/TagRepository.java
  src/main/java/com/umc/TheGoods/repository/TagSearchRepository.java
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/repository/item/ItemTagRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
  src/main/java/com/umc/TheGoods/web/controller/MemberController.java
Labels: :sparkles: feature

#89 [feature/85] 상품 데이터 세팅 API 구현
  src/main/java/com/umc/TheGoods/aws/s3/AmazonS3Manager.java
  src/main/java/com/umc/TheGoods/domain/images/ProfileImg.java
  src/main/java/com/umc/TheGoods/domain/item/Item.java
  src/main/java/com/umc/TheGoods/domain/item/ItemOption.java
  src/main/java/com/umc/TheGoods/domain/item/Tag.java
  src/main/java/com/umc/TheGoods/domain/mapping/Tag/CategoryTag.java
  src/main/java/com/umc/TheGoods/domain/member/Member.java
  src/main/java/com/umc/TheGoods/domain/mypage/ContactTime.java
  src/main/java/com/umc/TheGoods/domain/mypage/Revenue.java
  src/main/java/com/umc/TheGoods/domain/mypage/WithdrawReason.java
  src/main/java/com/umc/TheGoods/repository/TagRepository.java
  src/main/java/com/umc/TheGoods/repository/item/CategoryTagRepository.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/UtilService.java
  src/main/java/com/umc/TheGoods/test/TestController.java
  src/main/java/com/umc/TheGoods/test/TestConverter.java
  src/main/java/com/umc/TheGoods/test/TestRequestDTO.java
  src/main/java/com/umc/TheGoods/test/TestResponseDTO.java
  src/main/java/com/umc/TheGoods/test/service/TestCommandService.java
  src/main/java/com/umc/TheGoods/test/service/TestCommandServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#97 🔨[refactor] 상품 등록 이미지 등록 및 썸네일 출력
  src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
  src/main/java/com/umc/TheGoods/converter/item/ItemImageConverter.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/test/TestController.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
  src/main/java/com/umc/TheGoods/web/dto/item/ItemRequestDTO.java
Labels: :recycle: refactor

#101 :bug: Bugfix: 태그 검색 오류 수정
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
Labels: :bug: bug

#103 🔨[refactor] 상품 검색 및 조회 validator 수정
  src/main/java/com/umc/TheGoods/repository/member/CategoryRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/validation/validator/ItemExistValidator.java
Labels: :recycle: refactor

#105 [feature/58] 결제 인증 및 승인 처리 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/umc/TheGoods/TheGoodsApplication.java
  src/main/java/com/umc/TheGoods/config/IamportConfig.java
  src/main/java/com/umc/TheGoods/domain/Payment.java
  src/main/java/com/umc/TheGoods/domain/common/BaseDateTimeEntity.java
  src/main/java/com/umc/TheGoods/domain/member/Member.java
  src/main/java/com/umc/TheGoods/domain/order/Orders.java
  src/main/java/com/umc/TheGoods/domain/payment/Payment.java
  src/main/java/com/umc/TheGoods/domain/payment/PaymentStatus.java
  src/main/java/com/umc/TheGoods/repository/.gitkeep
  src/main/java/com/umc/TheGoods/repository/payment/PaymentRepository.java
  src/main/java/com/umc/TheGoods/repository/post/PostRepository.java
  src/main/java/com/umc/TheGoods/service/PaymentService/PaymentService.java
  src/main/java/com/umc/TheGoods/service/PaymentService/PaymentServiceImpl.java
  src/main/java/com/umc/TheGoods/service/PostService/PostQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/PaymentController.java
  src/main/java/com/umc/TheGoods/web/controller/PostController.java
  src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/payment/PaymentCallbackRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/payment/PaymentRequest.java
  src/main/java/com/umc/TheGoods/web/dto/payment/PaymentRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/payment/PaymentResponseDTO.java
Labels: :sparkles: feature

#109 :bug: BugFix: 주문 내역 조회 API 오류 수정
  src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
Labels: :bug: bug

#111 :bug: BugFix: CI/CD 오류 수정
  src/main/java/com/umc/TheGoods/TheGoodsApplication.java
Labels: :computer: ci

#112 [ci/cd] 포트원 환경변수 설정 및 ci/cd 에러 해결
  .github/workflows/dev_deploy.yml
  src/main/java/com/umc/TheGoods/TheGoodsApplication.java
  src/main/java/com/umc/TheGoods/web/controller/PaymentController.java
  src/main/resources/application-dev.yml
Labels: :computer: ci

#114 ♻️ Refactor: PaymentController 주석 수정
  src/main/java/com/umc/TheGoods/web/controller/PaymentController.java
Labels: :computer: ci

#116 :recycle: Refactor: 장바구니 내역 조회, 주문 내역 조회 API 수정
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
Labels: :recycle: refactor

#117 :sparkles: Feat: 신상품/인기상품/마감임박상품 조회 API 구현
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#118 ✨ [feature] 방금 전 본 상품과 유사한 상품 추천 기능 구현
  src/main/java/com/umc/TheGoods/repository/item/ItemViewRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#121 ♻️ Refactor: 결제 승인 API 엔드포인트 및 swagger 명세 수정
  src/main/java/com/umc/TheGoods/config/IamportConfig.java
  src/main/java/com/umc/TheGoods/web/controller/PaymentController.java
Labels: :recycle: refactor

#122 🚀 [feature] 태그가 많이 등록된 상품 조회 API 구현
  src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
  src/main/java/com/umc/TheGoods/domain/item/Item.java
  src/main/java/com/umc/TheGoods/repository/item/ItemTagRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
  src/main/java/com/umc/TheGoods/web/dto/item/ConsultResultDTO.java
Labels: :sparkles: feature

#124 :recycle: Refactor: 상품 데이터 세팅 API 수정
  src/main/java/com/umc/TheGoods/domain/images/ProfileImg.java
  src/main/java/com/umc/TheGoods/domain/member/Member.java
  src/main/java/com/umc/TheGoods/repository/item/CategoryTagRepository.java
  src/main/java/com/umc/TheGoods/test/TestController.java
  src/main/java/com/umc/TheGoods/test/TestConverter.java
  src/main/java/com/umc/TheGoods/test/service/TestCommandServiceImpl.java
Labels: :recycle: refactor

#126 :recycle: Refactor: 장바구니 조회 API 응답 DTO 수정
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java
Labels: :recycle: refactor

#129 🔨[refactor] 상품 조회 응답 값 수정, 태그 검색 페이징 수정, 상품 검색 검증 수정
  src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/dto/item/ItemResponseDTO.java
Labels: :recycle: refactor

#131 🚀 [feature] 라스트 찬스, 배송예정일 순으로 상품 추천 기능 API 구현
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#132 :sparkles: Feat: 가장 많이 판매된 상품 조회 API 구현
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#135 [feature/133] 꾸준히 사랑받는 상품 추천 API 구현
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#140 :Recycle: Refactor: 이메일 찾기 api 수정
  src/main/java/com/umc/TheGoods/config/WebConfig.java
  src/main/java/com/umc/TheGoods/web/controller/MemberController.java
Labels: :recycle: refactor

#142 [feature/137] 오늘의 상품 추천 API 구현
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#141 🚀 [feature] 상품 검색 정렬 기능 API 구현
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#144 [feature/143] 관련 상품 조회 API 구현
  src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
  src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :sparkles: feature

#146 :bug: BugFix: 관련 상품 조회 API 페이징 오류 수정
  src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
Labels: :bug: bug

#147 [feature/127] 장바구니 옵션 수정, 삭제 API 구현
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/domain/order/Cart.java
  src/main/java/com/umc/TheGoods/domain/order/CartDetail.java
  src/main/java/com/umc/TheGoods/repository/cart/CartDetailRepository.java
  src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/CartController.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java
Labels: :sparkles: feature

#150 :sparkles: Feat: 장바구니 옵션, 상품 재고 조회 API 구현
  src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java
  src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/CartController.java
  src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java
Labels: :sparkles: feature

#151 :recycle: Refactor: 회원 정보 조회, 수정 api 기능 수정
  src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
  src/main/java/com/umc/TheGoods/domain/member/Member.java
  src/main/java/com/umc/TheGoods/domain/mypage/Account.java
  src/main/java/com/umc/TheGoods/domain/mypage/Address.java
  src/main/java/com/umc/TheGoods/repository/member/AccountRepository.java
  src/main/java/com/umc/TheGoods/repository/member/AddressRepository.java
  src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/MemberController.java
  src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
Labels: :recycle: refactor

#152 :recycle: Refactor: 프로필 조회 response 수정, 계좌 배송지 다중 등록 가능하게 변경
  src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
  src/main/java/com/umc/TheGoods/domain/mypage/Account.java
  src/main/java/com/umc/TheGoods/domain/mypage/Address.java
  src/main/java/com/umc/TheGoods/repository/member/AccountRepository.java
  src/main/java/com/umc/TheGoods/repository/member/AddressRepository.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java
  src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/umc/TheGoods/web/controller/MemberController.java
  src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java
  src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
Labels: :recycle: refactor

#154 :recycle: Refactor: 주문 등록 시 주문 상태 결제 완료로 변경
  src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
Labels: :recycle: refactor
